#!/bin/sh

# System initialization sequence:
#
# /init (this file)
#  |
#  +--(1) /etc/01_prepare.sh
#  |
#  +--(2) /etc/02_overlay.sh
#          |
#          +-- /etc/03_init.sh
#               |
#               +-- /sbin/init
#                    |
#                    +--(1) /etc/04_bootscript.sh
#                    |       |
#                    |       +-- /etc/autorun/* (all scripts)
#                    |
#                    +--(2) /bin/sh (Alt + F1, main console)
#                    |
#                    +--(2) /bin/sh (Alt + F2)
#                    |
#                    +--(2) /bin/sh (Alt + F3)
#                    |
#                    +--(2) /bin/sh (Alt + F4)

echo -e "Welcome to \\e[1mHVL \\e[32mLoader \\e[0m"

# Let's mount all core file systems.
/etc/01_prepare.sh

# Print first message on screen.
#cat /etc/msg/init_01.txt

# Wait 5 second or until any ~keyboard key is pressed.
key="s"
ip link set eth0 up
ip addr add $(cat /proc/cmdline | awk -Fnet= '{ print $2 }' | awk '{ print $1 }') brd + dev eth0
mkdir /nfs
mount -o vers=4 10.10.11.1:/nfs /nfs
#parted -s -a optimal /dev/sda mklabel gpt unit MB mkpart primary fat32 1024 1536 set 1 esp on mkpart primary ntfs 1536 33536 mkpart primary ext4 33792 63792 print
#mkfs.vfat -n System /dev/sda1
#mkntfs -Q -L AppSys /dev/sda2

mkdir /app
ntfs-3g /dev/sda2 /app

mkdir /efi
mount -o rw /dev/sda1 /efi
#wimapply /nfs/winpe.wim 1 /app
if [ ! "$key" = "" ] ; then
  # Print second message on screen.
  #cat /etc/msg/init_02.txt
  #hello
  # Set flag which indicates that we have obtained controlling terminal.
  export PID1_SHELL=true

  # Interactive shell with controlling tty as PID 1.
  exec setsid cttyhack sh
fi

# Create new mountpoint in RAM, make it our new root location and overlay it
# with our storage area (if overlay area exists at all). This operation invokes
# the script '/etc/03_init.sh' as the new init process.
exec /etc/02_overlay.sh

echo "(/init) - you can never see this unless there is a serious bug."

# Wait until any key has been pressed.
read -n1 -s
